# Generated by Django 6.0.5 on 2026-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Если True — пользователь получает уведомления через Telegram', verbose_name='Подписан на уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Уникальный ID чата пользователя в Telegram', null=True, unique=True, verbose_name='ID чата Telegram'),
        ),
    ]
