# Generated by Django 6.0.5 on 2026-07-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_subscribed_user_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
    ]
