# Generated by Django 6.0.3 on 2026-05-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('yandex_market', 'Яндекс.Маркет')], max_length=20, verbose_name='Маркетплейс')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_competitors', to='store.product')),
            ],
            options={
                'verbose_name': 'Цена конкурента',
                'verbose_name_plural': 'Цены конкурентов',
                'unique_together': {('product', 'marketplace')},
            },
        ),
    ]
