# Generated by Django 6.0.3 on 2026-05-12 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_pricecomparison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecomparison',
            options={'verbose_name': 'Цена у конкурента', 'verbose_name_plural': 'Цены у конкурентов'},
        ),
        migrations.AddField(
            model_name='pricecomparison',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 12, 14, 36, 32, 354635, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricecomparison',
            name='image',
            field=models.URLField(blank=True, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='pricecomparison',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='pricecomparison',
            name='marketplace',
            field=models.CharField(choices=[('books_to_scrape', 'BooksToScrape'), ('google_books', 'Google Книги')], max_length=20),
        ),
    ]
