# Generated by Django 6.0.3 on 2026-04-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
