# Generated by Django 6.0.5 on 2026-05-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Доставка курьером')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Онлайн-оплата картой')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('cancelled', 'Отменён')], default='created', max_length=20),
        ),
    ]
