"""
Django settings for newprod project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z+w$_!drfy2@*2epn+7!77hj4#1%c(y01dm%i(()2=-odq0^o_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'store.apps.StoreConfig',
    'users.apps.UsersConfig',
    'django_dump_load_utf8',
    'social_django',
    'django_vite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'newprod.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'newprod.context_processors.categories_context',
                'newprod.context_processors.cart_context',
                # social auth context processor
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'newprod.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.yandex.YandexOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
DJANGO_VITE = {
    "default": {
        "dev_mode": True,
        "dev_server_protocol": "http",
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
        "static_url_prefix": "react",
    }
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'drf_spectacular': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
INTERNAL_IPS = ['127.0.0.1', 'localhost']
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {'max_connections': 50},
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'newprod',
    }
}
# Добавь fallback: если Redis упал — использовать локальный кеш
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True
DJANGO_REDIS_IGNORE_EXCEPTIONS = True

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_BEAT_SCHEDULE = {
    'update-price-comparison-daily': {
        'task': 'store.tasks.task_update_all_price_comparisons',
        'schedule': 60 * 60 * 24,
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # ← JWT вместо сессий
        # 'rest_framework.authentication.SessionAuthentication',  # можно оставить для браузера
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # 🔥 Подключаем Spectacular как стандартный renderer
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Токен живёт 60 минут
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Обновлять можно 7 дней
    'ROTATE_REFRESH_TOKENS': True,  # Старый refresh отменяется при обновлении
    'BLACKLIST_AFTER_ROTATION': True,  # Добавлять в чёрный список
    'UPDATE_LAST_LOGIN': True,  # Обновлять last_login

    'ALGORITHM': 'HS256',  # Алгоритм шифрования
    'SIGNING_KEY': SECRET_KEY,  # Ключ из Django
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),  # Заголовок: Authorization: Bearer <токен>
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
# settings.py

SPECTACULAR_SETTINGS = {
    'TITLE': 'ВИКИ API',
    'DESCRIPTION': 'API для магазина техники ВИКИ',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    # 🔐 Поддержка JWT
    'SECURITY': [{
        'BearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    }],
    'SECURITY_DEFINITIONS': {
        'BearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    },
}

LOGIN_URL = '/users/login/'
AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# youkassa
YOOKASSA_SHOP_ID = '1360170'
YOOKASSA_SECRET_KEY = 'test_HjKUY6Ta8-AP0vV6DlM_LXCcKvu0gReVxwXCMyBLuxc'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# social auth configs for github
SOCIAL_AUTH_GITHUB_KEY = 'Ov23lituFgUhJdHaGrFF'
SOCIAL_AUTH_GITHUB_SECRET = 'ff2c53a1d9bd934e512ad8ac87110bdab65d7b31'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '48328434690-8dvgf5hd33d8rqd4ss5158b058evp1hv.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kostya.barnung@gmail.com'
EMAIL_HOST_PASSWORD = 'mdxz jspq yelo cajc'
DEFAULT_FROM_EMAIL = 'kostya.barnung@gmail.com'

# Yandex OAuth2
SOCIAL_AUTH_YANDEX_OAUTH2_KEY = '3adaa4af6dc845229bc521dcd36e7106'
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = '7ab4638d92c344ee9f2648f603f8a899'
# Опционально: какие данные запрашивать
SOCIAL_AUTH_YANDEX_OAUTH2_SCOPE = [
    'login:email',
    'login:info',
]
# Фикс: Яндекс может не возвращать email — принудительно запросим
SOCIAL_AUTH_YANDEX_OAUTH2_EXTRA_DATA = ['emails']

# Статика
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
